const colleges = [
    { name: "All India Institute of Medical Sciences (AIIMS) Deoghar", address: "Deoghar, Jharkhand" },
    { name: "Anugrah Narayan College (AN College)", address: "Patna, Bihar" },
    { name: "Arcades Business College", address: "Patna, Bihar" },
    { name: "Atal Bihari Vajpayee Indian Institute of Information Technology and Management (IIITM) Gwalior", address: "Gwalior, Madhya Pradesh" },
    { name: "B. N. College", address: "Patna, Bihar" },
    { name: "B.S. College", address: "Danapur, Patna, Bihar" },
    { name: "Bakhtiyarpur College of Engineering", address: "Bakhtiyarpur, Bihar" },
    { name: "Bihar Young Men's Institute", address: "Patna, Bihar" },
    { name: "Birla Institute of Technology (BIT) Sindri", address: "Dhanbad, Jharkhand" },
    { name: "Birla Institute of Technology, Mesra (Patna Campus)", address: "Patna, Bihar" },
    { name: "Creane Memorial High School", address: "Gaya, Bihar" },
    { name: "Dr. B. R. Ambedkar National Institute of Technology (NIT) Jalandhar", address: "Jalandhar, Punjab" },
    { name: "G.D. Mother International School", address: "Muzaffarpur, Bihar" },
    { name: "Gaya College of Engineering", address: "Gaya, Bihar" },
    { name: "Government Engineering College, Banka", address: "Banka, Bihar" },
    { name: "Government Engineering College, Lakhisarai", address: "Lakhisarai, Bihar" },
    { name: "IMS Design and Innovation Academy", address: "Noida, Uttar Pradesh" },
    { name: "Indian Institute of Carpet Technology", address: "Bhadohi, Uttar Pradesh" },
    { name: "Indian Institute of Engineering Science and Technology, Shibpur", address: "Howrah, West Bengal" },
    { name: "Indian Institute of Information Technology (IIIT) Agartala", address: "Agartala, Tripura" },
    { name: "Indian Institute of Information Technology (IIIT) Allahabad", address: "Prayagraj, Uttar Pradesh" },
    { name: "Indian Institute of Information Technology (IIIT) Bhagalpur", address: "Bhagalpur, Bihar" },
    { name: "Indian Institute of Information Technology (IIIT) Bhopal", address: "Bhopal, Madhya Pradesh" },
    { name: "Indian Institute of Information Technology (IIIT) Dharwad", address: "Dharwad, Karnataka" },
    { name: "Indian Institute of Information Technology (IIIT) Guwahati", address: "Guwahati, Assam" },
    { name: "Indian Institute of Information Technology (IIIT) Kalyani", address: "Kalyani, West Bengal" },
    { name: "Indian Institute of Information Technology (IIIT) Kota", address: "Kota, Rajasthan" },
    { name: "Indian Institute of Information Technology (IIIT) Kottayam", address: "Kottayam, Kerala" },
    { name: "Indian Institute of Information Technology (IIIT) Lucknow", address: "Lucknow, Uttar Pradesh" },
    { name: "Indian Institute of Information Technology (IIIT) Nagpur", address: "Nagpur, Maharashtra" },
    { name: "Indian Institute of Information Technology (IIIT) Pune", address: "Pune, Maharashtra" },
    { name: "Indian Institute of Information Technology (IIIT) Raichur", address: "Raichur, Karnataka" },
    { name: "Indian Institute of Information Technology (IIIT) Ranchi", address: "Ranchi, Jharkhand" },
    { name: "Indian Institute of Information Technology (IIIT) Sonepat", address: "Sonepat, Haryana" },
    { name: "Indian Institute of Information Technology (IIIT) Sri City", address: "Sri City, Andhra Pradesh" },
    { name: "Indian Institute of Information Technology (IIIT) Surat", address: "Surat, Gujarat" },
    { name: "Indian Institute of Information Technology (IIIT) Tiruchirappalli", address: "Tiruchirappalli, Tamil Nadu" },
    { name: "Indian Institute of Information Technology (IIIT) Una", address: "Una, Himachal Pradesh" },
    { name: "Indian Institute of Information Technology (IIIT) Vadodara", address: "Vadodara, Gujarat" },
    { name: "Indian Institute of Information Technology, Design and Manufacturing (IIITDM) Jabalpur", address: "Jabalpur, Madhya Pradesh" },
    { name: "Indian Institute of Information Technology, Design and Manufacturing (IIITDM) Kancheepuram", address: "Kancheepuram, Tamil Nadu" },
    { name: "Indian Institute of Information Technology, Design and Manufacturing (IIITDM) Kurnool", address: "Kurnool, Andhra Pradesh" },
    { name: "Indian Institute of Management (IIM) Ahmedabad", address: "Ahmedabad, Gujarat" },
    { name: "Indian Institute of Management (IIM) Bangalore", address: "Bengaluru, Karnataka" },
    { name: "Indian Institute of Management (IIM) Calcutta", address: "Kolkata, West Bengal" },
    { name: "Indian Institute of Management (IIM) Indore", address: "Indore, Madhya Pradesh" },
    { name: "Indian Institute of Management (IIM) Kozhikode", address: "Kozhikode, Kerala" },
    { name: "Indian Institute of Management (IIM) Lucknow", address: "Lucknow, Uttar Pradesh" },
    { name: "Indian Institute of Management (IIM) Raipur", address: "Raipur, Chhattisgarh" },
    { name: "Indian Institute of Management (IIM) Ranchi", address: "Ranchi, Jharkhand" },
    { name: "Indian Institute of Management (IIM) Tiruchirappalli", address: "Tiruchirappalli, Tamil Nadu" },
    { name: "Indian Institute of Management (IIM) Udaipur", address: "Udaipur, Rajasthan" },
    { name: "Indian Institute of Technology (IIT BHU) Varanasi", address: "Varanasi, Uttar Pradesh" },
    { name: "Indian Institute of Technology (IIT ISM) Dhanbad", address: "Dhanbad, Jharkhand" },
    { name: "Indian Institute of Technology (IIT) Bhilai", address: "Bhilai, Chhattisgarh" },
    { name: "Indian Institute of Technology (IIT) Bhubaneswar", address: "Bhubaneswar, Odisha" },
    { name: "Indian Institute of Technology (IIT) Bombay", address: "Mumbai, Maharashtra" },
    { name: "Indian Institute of Technology (IIT) Delhi", address: "New Delhi, Delhi" },
    { name: "Indian Institute of Technology (IIT) Dharwad", address: "Dharwad, Karnataka" },
    { name: "Indian Institute of Technology (IIT) Gandhinagar", address: "Gandhinagar, Gujarat" },
    { name: "Indian Institute of Technology (IIT) Goa", address: "Ponda, Goa" },
    { name: "Indian Institute of Technology (IIT) Guwahati", address: "Guwahati, Assam" },
    { name: "Indian Institute of Technology (IIT) Hyderabad", address: "Hyderabad, Telangana" },
    { name: "Indian Institute of Technology (IIT) Indore", address: "Indore, Madhya Pradesh" },
    { name: "Indian Institute of Technology (IIT) Jammu", address: "Jammu, Jammu and Kashmir" },
    { name: "Indian Institute of Technology (IIT) Jodhpur", address: "Jodhpur, Rajasthan" },
    { name: "Indian Institute of Technology (IIT) Kanpur", address: "Kanpur, Uttar Pradesh" },
    { name: "Indian Institute of Technology (IIT) Kharagpur", address: "Kharagpur, West Bengal" },
    { name: "Indian Institute of Technology (IIT) Madras", address: "Chennai, Tamil Nadu" },
    { name: "Indian Institute of Technology (IIT) Mandi", address: "Mandi, Himachal Pradesh" },
    { name: "Indian Institute of Technology (IIT) Palakkad", address: "Palakkad, Kerala" },
    { name: "Indian Institute of Technology (IIT) Roorkee", address: "Roorkee, Uttarakhand" },
    { name: "Indian Institute of Technology (IIT) Ropar", address: "Rupnagar, Punjab" },
    { name: "Indian Institute of Technology (IIT) Tirupati", address: "Tirupati, Andhra Pradesh" },
    { name: "Indira Gandhi National Open University (Regional Centre)", address: "Patna, Bihar" },
    { name: "Indira Gandhi National Tribal University", address: "Amarkantak, Madhya Pradesh" },
    { name: "Institute of Infrastructure Technology Research and Management", address: "Ahmedabad, Gujarat" },
    { name: "Institute of Medical Sciences, Banaras Hindu University (IMS BHU)", address: "Varanasi, Uttar Pradesh" },
    { name: "Integral Institute of Medical Sciences and Research (IIMSR)", address: "Lucknow, Uttar Pradesh" },
    { name: "Jagat Narayan Lal College", address: "Khagaul, Patna, Bihar" },
    { name: "Jagjivan College", address: "Ara, Bihar" },
    { name: "Loknayak Jai Prakash Institute of Technology (LNJPIT)", address: "Chhapra, Bihar" },
    { name: "Maharaja College", address: "Ara, Bihar" },
    { name: "Malaviya National Institute of Technology (MNIT) Jaipur", address: "Jaipur, Rajasthan" },
    { name: "Maulana Azad National Institute of Technology (MANIT) Bhopal", address: "Bhopal, Madhya Pradesh" },
    { name: "Motihari College of Engineering", address: "Motihari, Bihar" },
    { name: "Motilal Nehru National Institute of Technology (MNNIT) Allahabad", address: "Prayagraj, Uttar Pradesh" },
    { name: "Nalanda College of Engineering", address: "Chandi, Bihar" },
    { name: "National Institute of Technology (NIT) Agartala", address: "Agartala, Tripura" },
    { name: "National Institute of Technology (NIT) Andhra Pradesh", address: "Tadepalligudem, Andhra Pradesh" },
    { name: "National Institute of Technology (NIT) Arunachal Pradesh", address: "Yupia, Arunachal Pradesh" },
    { name: "National Institute of Technology (NIT) Calicut", address: "Kozhikode, Kerala" },
    { name: "National Institute of Technology (NIT) Delhi", address: "New Delhi, Delhi" },
    { name: "National Institute of Technology (NIT) Durgapur", address: "Durgapur, West Bengal" },
    { name: "National Institute of Technology (NIT) Goa", address: "Ponda, Goa" },
    { name: "National Institute of Technology (NIT) Hamirpur", address: "Hamirpur, Himachal Pradesh" },
    { name: "National Institute of Technology (NIT) Jamshedpur", address: "Jamshedpur, Jharkhand" },
    { name: "National Institute of Technology (NIT) Kurukshetra", address: "Kurukshetra, Haryana" },
    { name: "National Institute of Technology (NIT) Manipur", address: "Imphal, Manipur" },
    { name: "National Institute of Technology (NIT) Meghalaya", address: "Shillong, Meghalaya" },
    { name: "National Institute of Technology (NIT) Mizoram", address: "Aizawl, Mizoram" },
    { name: "National Institute of Technology (NIT) Nagaland", address: "Chümoukedima, Nagaland" },
    { name: "National Institute of Technology (NIT) Patna", address: "Patna, Bihar" },
    { name: "National Institute of Technology (NIT) Puducherry", address: "Karaikal, Puducherry" },
    { name: "National Institute of Technology (NIT) Raipur", address: "Raipur, Chhattisgarh" },
    { name: "National Institute of Technology (NIT) Rourkela", address: "Rourkela, Odisha" },
    { name: "National Institute of Technology (NIT) Sikkim", address: "Ravangla, Sikkim" },
    { name: "National Institute of Technology (NIT) Silchar", address: "Silchar, Assam" },
    { name: "National Institute of Technology (NIT) Srinagar", address: "Srinagar, Jammu and Kashmir" },
    { name: "National Institute of Technology (NIT) Tiruchirappalli", address: "Tiruchirappalli, Tamil Nadu" },
    { name: "National Institute of Technology (NIT) Uttarakhand", address: "Srinagar, Uttarakhand" },
    { name: "National Institute of Technology (NIT) Warangal", address: "Warangal, Telangana" },
    { name: "National Institute of Technology Karnataka (NITK) Surathkal", address: "Mangalore, Karnataka" },
    { name: "Netaji Subhas Medical College and Hospital", address: "Bihta, Patna, Bihar" },
    { name: "Patna Science College", address: "Patna, Bihar" },
    { name: "Patna University", address: "Patna, Bihar" },
    { name: "R.S. Group of College", address: "Shekhapur, Akharaghat Chowk, Muzaffarpur" },
    { name: "Sardar Vallabhbhai National Institute of Technology (SVNIT) Surat", address: "Surat, Gujarat" },
    { name: "Shershah College of Engineering", address: "Sasaram, Bihar" },
    { name: "St. Xavier's College of Management and Technology", address: "Patna, Bihar" },
    { name: "Supaul College of Engineering", address: "Supaul, Bihar" },
    { name: "Vestor College of Management", address: "Zeromile, Patna (Behind Krishna Niketan School)" },
    { name: "Visvesvaraya National Institute of Technology (VNIT) Nagpur", address: "Nagpur, Maharashtra" }
];

export default colleges;